name: Deploy StorageApp Frontend
on: [push, workflow_dispatch]

jobs:
  job:
    runs-on: ubuntu-latest

    env: 
      VITE_API_URL: https://api.govindsahu.me
      VITE_GOOGLE_AUTH_CLIENT_ID: 1080347041084-ql6qrkks5ucvunc56fu3qgkkbogniuic.apps.googleusercontent.com
      
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "23"

      - name: Clone GitHub Repository
        uses: actions/checkout@v4
      - run: npm ci --no-audit --no-fund
      - run: npm run test
      - run: npm run build

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - run: aws s3 sync "/home/runner/work/StorageApp-Frontend/StorageApp-Frontend/dist" s3://storage-app-frontend --delete
      - run: aws cloudfront create-invalidation --distribution-id ET2RX5F4BTHHS --paths "/index.html"
